version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: food-delivery-redis
    ports:
      - "16380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass fooddelivery@2024
    networks:
      - food-delivery-network
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

  rabbitmq:
    image: rabbitmq:3-management
    container_name: food-delivery-rabbitmq
    ports:
      - "6000:5672"   # RabbitMQ standard port
      - "15672:15672" # Management interface port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - food-delivery-network
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=guest      # Bạn có thể thay đổi username
      - RABBITMQ_DEFAULT_PASS=guest      # Bạn có thể thay đổi password
      - TZ=Asia/Ho_Chi_Minh

volumes:
  redis_data:
  rabbitmq_data:

networks:
  food-delivery-network:
    driver: bridge