version: '3.8'

services:
  app:
    image: ${CI_REGISTRY_IMAGE}:${IMAGE_TAG}
    container_name: food-delivery-app
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Ho_Chi_Minh
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - OPENROUTE_API_KEY=${OPENROUTE_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}
      - TMN_CODE=${TMN_CODE}
      - VNPAY_SECRET_KEY=${VNPAY_SECRET_KEY}
    ports:
      - "8118:8118"
    networks:
      - food-delivery-network

networks:
  food-delivery-network:
    driver: bridge


