version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: food-delivery-redis
    ports:
      - "16380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass fooddelivery@2024
    networks:
      - food-delivery-network
    restart: unless-stopped
    environment:
      - TZ=Asia/Ho_Chi_Minh

volumes:
  redis_data:

networks:
  food-delivery-network:
    driver: bridge
