spring:

  application:
    name: food-delivery-back-end
  datasource:
    url: jdbc:mysql://localhost:3306/food_delivery?createDatabaseIfNotExist=true
    username: ${DB_USERNAME} #root
    password: ${DB_PASSWORD} #123456
  jpa:
    hibernate:
      ddl-auto: update # create-drop, create, update, validate, none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 6000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}


api:
  prefix: /api/v1

file:
  upload-dir: upload

openrouteservice:
  api:
    key: ${OPENROUTE_API_KEY}

jwtSecret: ${JWT_SECRET_KEY}
jwtExpirationMs: ${JWT_EXPIRATION_TIME}

server:
  port: 8118

vnpay:
  pay-url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
  return-url: "http://localhost:5173/vnpay-return"
  tmn-code: ${TMN_CODE}
  hash-secret: ${VNPAY_SECRET_KEY}
  api-url: "https://sandbox.vnpayment.vn/merchant_webapi/api/transaction"